import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const INTER = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={INTER.className}>{children}</body>
        </html>
    );
}
